data:extend(
{
  {
    type = "item",
    name = "zinc-plate",
    icon = "__Factorio-Resources__/graphics/zinc/plate-icon.png",
    flags = {"goes-to-main-inventory"},
    subgroup = "resources-plates",
    order = "zinc",
    stack_size = 200,
  },
  {
    type = "item",
    name = "tin-plate",
    icon = "__Factorio-Resources__/graphics/tin/plate-icon.png",
    flags = {"goes-to-main-inventory"},
    subgroup = "resources-plates",
    order = "tin",
    stack_size = 200,
  },
  {
    type = "item",
    name = "silver-plate",
    icon = "__Factorio-Resources__/graphics/silver/plate-icon.png",
    flags = {"goes-to-main-inventory"},
    subgroup = "resources-plates",
    order = "silver",
    stack_size = 200,
  },
  {
    type = "item",
    name = "lead-plate",
    icon = "__Factorio-Resources__/graphics/lead/plate-icon.png",
    flags = {"goes-to-main-inventory"},
    subgroup = "resources-plates",
    order = "lead",
    stack_size = 200,
  },
  {
    type = "item",
    name = "tungsten-plate",
    icon = "__Factorio-Resources__/graphics/tungsten/plate-icon.png",
    flags = {"goes-to-main-inventory"},
    subgroup = "resources-plates",
    order = "tungsten",
    stack_size = 200,
  },
  {
    type = "item",
    name = "gold-plate",
    icon = "__Factorio-Resources__/graphics/gold/plate-icon.png",
    flags = {"goes-to-main-inventory"},
    subgroup = "resources-plates",
    order = "gold",
    stack_size = 200,
  },
  {
    type = "item",
    name = "cobalt-plate",
    icon = "__Factorio-Resources__/graphics/cobalt/plate-icon.png",
    flags = {"goes-to-main-inventory"},
    subgroup = "resources-plates",
    order = "cobalt",
    stack_size = 200,
  },
  {
    type = "item",
    name = "ardite-plate",
    icon = "__Factorio-Resources__/graphics/ardite/plate-icon.png",
    flags = {"goes-to-main-inventory"},
    subgroup = "resources-plates",
    order = "ardite",
    stack_size = 200,
  },
}
)
